name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install -g npm@7 && npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run coverage
      - name: Report coverage
        uses: codecov/codecov-action@v1.2.1
