name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          cache: npm
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run coverage
      - name: Report coverage
        uses: codecov/codecov-action@v3.1.1
