name: Publish
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.5.1
        with:
          cache: npm
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install -g npm@9 && npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
